[package]
name = "photomanager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "A GNOME application for managing the data of a personal photo library."

[lib]
name = "photomanager"
path = "src/lib.rs"

[[bin]]
name = "photomanager"
path = "src/main.rs"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_9"] }
gtk = { version = "0.11.5", package = "gtk4", features = ["v4_20"] }
photomanager-core.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = { version = "1", optional = true }
async-channel = "2.5.0"
glycin = { version = "4.0.0", features = ["gdk4"] }
shumate = { version = "0.8.1", package = "libshumate", features = ["v1_6"] }

[dev-dependencies]
serde_json = "1"
photomanager-core = { workspace = true, features = ["fixtures"] }

[features]
devtools = ["dep:serde_json"]

[build-dependencies]
glib-build-tools = "0.22.8"
