[package]
name = "photomanager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "photomanager"
path = "src/lib.rs"

[[bin]]
name = "photomanager"
path = "src/main.rs"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_9"] }
gtk = { version = "0.11.5", package = "gtk4", features = ["v4_20"] }
photomanager-core.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
devtools = []

[build-dependencies]
glib-build-tools = "0.22.8"
